services:
  prechecks:
    build:
      context: ./prechecks
    volumes:
      - ./.env:/app/.env
      - ./.env.example:/app/.env.example
    restart: no

  backend:
    build:
      context: ./backend
    stop_signal: SIGINT
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - FLASK_ENV=${ENV}
      - FRONTEND_URL=${FRONTEND_URL}
    ports: 
      - 8000:8000
    networks:
      - backend_network
    volumes:
      - ./backend:/app
    depends_on:
      - prechecks
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - astro_node_modules:/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - PUBLIC_BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
      - prechecks
    restart: on-failure


  db:
    image: postgres:17
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend_network
    depends_on:
      - prechecks

volumes:
  astro_node_modules:
  postgres-data:

networks:
  backend_network:
    driver: bridge
