services:
  prechecks:
    build:
      context: ./prechecks
    volumes:
      - ./.env:/app/.env
      - ./.env.example:/app/.env.example
    restart: no

  backend:
    build:
      context: ./backend
    stop_signal: SIGINT
    restart: always
    ports: 
      - 8000:8000
    depends_on:
      - prechecks

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - astro_node_modules:/app/node_modules
    ports:
      - 4321:4321
    env_file:
      - .env
    depends_on:
      - backend
      - prechecks
    restart: on-failure

volumes:
  astro_node_modules:
